apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR-USERNAME/argo-demo.git
    targetRevision: main
    path: apps/nginx/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-staging

  syncPolicy:
    automated:
      prune: true       # delete resources no longer in Git
      selfHeal: true    # fix drift automatically
    syncOptions:
      - CreateNamespace=true
