apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR-USERNAME/argo-demo.git
    targetRevision: main
    path: apps/nginx/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
